version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://apiuser:Tac0Salad1sH3althy@postgres:5432/users
      NODE_ENV: development
      JWT_SECRET: Sup3rS#cretStuff
      PORT: 8000
    ports:
      - 8000:8000
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres:10.4
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: Tac0Salad1sH3althy
      POSTGRES_DB: users