version: "3.7"

services:
  db:
    image: postgres:12.1
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./conf/db/init:/docker-entrypoint-initdb.d
  web:
    build: .
    restart: always
    env_file:
      - .env
    # Prevent gunicorn workers from blocking
    tmpfs: /tmp
    command: bash -c "gunicorn wsgi:app -b :8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  proxy:
    image: nginx:1.17.8
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web